### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vanissoft** [vanissoft/DEXhub#1]
Unordered list of features i wanted to add:

- [ ] List of assets in balances
- [ ] Price graph for every asset in balance 
- [ ] Market transaction listener
- [ ] Various markets for every asset in balance
- [ ] Cross valuation in base coin for every asset in every market
- [ ] Visual arrangements
- [ ] Graphic limit orders management

### Automation:
For bots there there will be conditions on % feed reference and segments buyers and sellers
- [ ] 1 time enter-exit (exit = enter+%)
- [ ] 1 time conditional entering (segments ratio)
- [ ] 1 time conditional exiting (segments ratio)
- [ ] continuous enter-exit 
- [ ] Cross-markets strategies
